# pod-with-node-affinity-multiple.yml
#
# First assign labels on all nodes in our cluster
#
# Confirm the labels
# kubectl get nodes --show-labels
#
apiVersion: v1
kind: Pod
metadata:
  name: app1
  namespace: learning
  labels:
   app: apache
spec:
  containers:
    - name: web
      image: lovelearnlinux/webserver:v1
      resources:
        limits:
          memory: "500Mi"
        requests:
          memory: "300Mi"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: size
            operator: In
            values:
            - large
            - medium


#
# Lets think we have some nodes with label small/medium/large
# We want this pod to be deployed on either pod having small
# OR medium label
#
# Confirm for the labels on nodes using:
#
# kubectl get nodes --show-labels 
#
# create namespace learning -
# kubectl create namespace learning
#
# run the pod
# kubectl create -f pod-with-node-affinity-multiple.yml
#
# check the pod
# kubectl get pods --namespace=learning --output=wide
#
# get details about pod
# kubectl describe pod app1 --namespace=learning
#
# check for the node where its running. It must be
# running on node having label size=small OR size=medium
# 
# delete pod
# kubectl delete pod app1 --namespace=learning
#
